name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        with:
          heroku_api_key: ed9ca221-3e3e-42cc-bc90-d0e8d427d8fb
          heroku_app_name: "iamshubot" #Must be unique in Heroku
          heroku_email: "unfezant211@gmail.com"
          docker_heroku_process_type: worker
